---
title: "16s Microbiome Analysis Workshop"
author: "Alana Schick"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
description: This workbook contains workshop material for all three days.
---

# Welcome {-}

The intention is to develop workshop material as we go along. For each day of the workshop, the basic material will be uploaded and more details will be added based on your questions and problems we encounter. So please ask as many questions as you can to help in making this workshop better!!

## Workshop Schedule {-}

We will try to cover the following material in the course. This may be ambitious, so expect this schedule to change, depending how things go.

### Day 1 {-}

Time | Topic                               
:-------| :----------------------------------
09:00  | Welcome, Housekeeping, and Introductions
09:10  | 1. Pre-workshop
09:30  | Presentation of basic concepts
10:00  | 2. Introduction
10:15  | Break
10:30  | 3. Removing primers
11:30  | Lunch break
12:00  | 4. Filter
13:00  | Finish

### Day 2 {-}

Time | Topic                                         
:-------| :----------------------------------
13:00  | 5. Denoise
13:30  | 6. Assign Taxonomy
14:00  | 7. Phyloseq - Preprocessing
14:30  | Break
15:00  | 7. Phyloseq - Preprocessing (cont)
15:30  | 8. Taxonomic Composition
16:00  | Finish

### Day 3 {-}

Time | Topic                                         
:-------| :----------------------------------
13:00  | 9. Alpha Diversity
13:45  | 10. Beta Diversity
14:30  | Break
15:00  | 11. Hypothesis Testing
16:00  | Finish


## Important links {-}

- Project dataset: [link](https://www.dropbox.com/s/glw1aig4jsyxuem/raw_data.zip?dl=0)
- DADA2 paper: [link](https://www.nature.com/articles/nmeth.3869#methods)
- DADA2 tutorial: [link](https://benjjneb.github.io/dada2/tutorial.html)
- Phyloseq tutorials: [link](https://joey711.github.io/phyloseq/)

